import excel "~\git\ProstateCancerFattyacid\DATA\original_data.xlsx", sheet("var") firstrow /*replace this line with your local path*/

*FADS1 SNP rs174556
export delimited rs174556 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174556_Af_controls.txt" if case==0 & race=="African" & rs174556 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174556 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174556_Af_cases.txt" if case==1 & race=="African" & rs174556 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174556 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174556_AA_controls.txt" if case==0 & race=="African American" & rs174556 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174556 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174556_AA_cases.txt" if case==1 & race=="African American" & rs174556 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174556 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174556_EA_controls.txt" if case==0 & race=="European American" & rs174556 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174556 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174556_EA_cases.txt" if case==1 & race=="European American" & rs174556 !="", delimiter(tab) replace /*replace the file path with your local path*/

*FADS2 SNP rs174583
export delimited rs174583 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174583_Af_controls.txt" if case==0 & race=="African" & rs174583 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174583 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174583_Af_cases.txt" if case==1 & race=="African" & rs174583 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174583 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174583_AA_controls.txt" if case==0 & race=="African American" & rs174583 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174583 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174583_AA_cases.txt" if case==1 & race=="African American" & rs174583 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174583 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174583_EA_controls.txt" if case==0 & race=="European American" & rs174583 !="", delimiter(tab) replace /*replace the file path with your local path*/
export delimited rs174583 fa_Behenic fa_Lignoceric fa_Myristic fa_Palmitic fa_Stearic fa_Eicosenoic fa_Nervonic fa_Oleic fa_Palmitoleic fa_alphaLinolenic fa_Docosahexaenoic fa_Docosapentaenoicn3 fa_Eicosapentaenoic fa_Arachidonic fa_Dihomoglinolenic fa_Docosapentaenoicn6 fa_Docosatetraenoic fa_Eicosadienoic fa_gammaLinolenic fa_Linoleic fa_Elaidic fa_Palmitelaidic fa_Linoelaidic using "~\git\ProstateCancerFattyacid\DATA\rs174583_EA_cases.txt" if case==1 & race=="European American" & rs174583 !="", delimiter(tab) replace /*replace the file path with your local path*/
